### ISSUE TITLE
Incompatibility issues with v1.5 of SAMtools and BCFtools

### ISSUE THREAD

**Issue by zadyson** [katholt/genotyphi#21]
We have found that running genotyphi.py with version 1.5 of SAMtools and BCFtools causes the following error:

```
Traceback (most recent call last):

  File "genotyphi.py", line 414, in <module>

    main()

  File "genotyphi.py", line 289, in main

    run_command(['samtools', 'faidx', 'temp_reference.fasta'])  # index fasta file

  File "genotyphi.py", line 250, in run_command

    raise CommandError({"message": message})

__main__.CommandError: {'message': "Command 'samtools faidx temp_reference.fasta' failed with non-zero exit status: 127"}
```

Versions 1.1-1.3 do not cause this issue.

**Comment by andersgs** [comment]
In trying to run your example, I ran into this issue (running `samtools 1.9`). But, it was because this bit of code silently failed to produce a FASTA file:
```
			with open(args.ref, 'r') as fasta_file: # create SAMtools compatible fasta file
				sequences = fasta_file.read()
				for sequence in sequences.split('>'):
					if args.ref_id in sequence:	
						new_header = '>' + args.ref_id
						replacement_index = sequence.find('\n')
						sequence = new_header + sequence[replacement_index:]
						with open('temp_reference.fasta', 'w') as temp_fasta_file: 
							temp_fasta_file.write(sequence)
```

Lines 317-325

This error occurred because NCBI changed the ID of the sequences in reference file (and the file location).

The new ID is: NC_003198.1
The new URI is: `ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/195/995/GCF_000195995.1_ASM19599v1/GCF_000195995.1_ASM19599v1_genomic.fna.gz`

For me, the following works: 
```# Download CT18 (AL513382) reference genome

wget -O CT18.fasta.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/195/995/GCF_000195995.1_ASM19599v1/GCF_000195995.1_ASM19599v1_genomic.fna.gz

gunzip CT18.fasta.gz

# Download reads for S. Typhi 8(04)N, isolated from Vietnam in 2004

wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR343/ERR343343/ERR343343_{1,2}.fastq.gz

# Use bowtie to map reads to the CT18 reference genome

# For example, to align paired end reads to the CT18 reference genome sequence:

bowtie2-build CT18.fasta CT18

# this works with samtools >=1.3 (tested on version 1.9)

bowtie2 -p 2 -x CT18 -1 ERR343343_1.fastq.gz -2 ERR343343_2.fastq.gz | samtools view -u - | samtools sort -o output.bam

# Call Typhi genotypes from the resulting BAM(s)

python3 ../genotyphi.py --mode bam --bam output.bam --ref CT18.fasta --ref_id NC_003198.1 --output genotypes_test.txt
```

Note that I use `python3` --- I first ran `2to3 -w genotyphi.py`.

**Comment by zadyson** [comment]
Thanks for picking this up Anders!
